name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    # Postgres konteynerini shu yerda yoqamiz
    services:
      postgres_db:
        image: postgres:15
        env:
          POSTGRES_DB: ${{ secrets.DATABASE_NAME }}  # O'zingiz xohlagan nom
          POSTGRES_USER: ${{ secrets.DATABASE_USER }}
          POSTGRES_PASSWORD: ${{ secrets.USER_PASSWORD }}
        ports:
        - 5432:5432

        # Postgres tayyor bo'lishini kutish uchun health check
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY_PORTFOLIO }}
      EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
      EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
      POSTGRES_DB: ${{ secrets.DATABASE_NAME }}
      POSTGRES_USER: ${{ secrets.DATABASE_USER }}
      POSTGRES_PASSWORD: ${{ secrets.USER_PASSWORD }}
      DATABASE_HOST: localhost  # GitHub runner uchun localhost deb yoziladi
      DATABASE_PORT: 5432
      DEBUG: "False"


    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: python manage.py test
  deploy:
    needs: build  # 1-qator: Build (testlar) muvaffaqiyatli o'tmaguncha ishga tushma
    runs-on: ubuntu-latest  # 2-qator: Bu buyruqlarni bajarish uchun virtual Ubuntu muhitini ishlat
    if: github.ref == 'refs/heads/main'  # 3-qator: Faqat 'main' branchiga kod kelganda ishla

    steps:
      - name: AWS EC2 ga SSH orqali ulanish
        uses: appleboy/ssh-action@master # 4-qator: SSH orqali serverga kirish uchun maxsus tayyor plagin
        with:
          host: ${{ secrets.HOST_DNS }}       # 5-qator: Serveringiz IP manzili (Secrets'dan olinadi)
          username: ec2-user   # 6-qator: Server user nomi (ubuntu yoki ec2-user)
          key: ${{ secrets.EC2_SSH_KEY }}     # 7-qator: .pem faylingiz ichidagi maxfiy kod
          script: |  # 8-qator: SSH orqali kirgandan keyin bajarilishi kerak bo'lgan buyruqlar ro'yxati
            cd /home/ec2-user/soyibjon-diplom-ishi  # 9-qator: Loyiha turgan papkaga kirish
            git pull origin main                      # 10-qator: GitHub'dagi yangi kodni serverga yuklab olish
            source .venv/bin/activate                 # 11-qator: Python virtual muhitini yoqish
            pip install -r requirements.txt           # 12-qator: Yangi kutubxonalar qo'shilgan bo'lsa, o'rnatish
            python manage.py migrate                  # 13-qator: Bazadagi o'zgarishlarni (model) qo'llash
            python manage.py collectstatic --noinput  # 14-qator: CSS, JS fayllarni statik papkaga yig'ish
            sudo systemctl restart gunicorn           # 15-qator: Gunicorn (server)ni yangi kod bilan qayta o't oldirish