name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    # Postgres konteynerini shu yerda yoqamiz
    services:
      postgres_db:
        image: postgres:15
        env:
          POSTGRES_DB: ${{ secrets.DATABASE_NAME }}  # O'zingiz xohlagan nom
          POSTGRES_USER: ${{ secrets.DATABASE_USER }}
          POSTGRES_PASSWORD: ${{ secrets.USER_PASSWORD }}
        ports:
        - 5432:5432

        # Postgres tayyor bo'lishini kutish uchun health check
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY_PORTFOLIO }}
      EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
      EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
      POSTGRES_DB: ${{ secrets.DATABASE_NAME }}
      POSTGRES_USER: ${{ secrets.DATABASE_USER }}
      POSTGRES_PASSWORD: ${{ secrets.USER_PASSWORD }}
      DATABASE_HOST: localhost  # GitHub runner uchun localhost deb yoziladi
      DATABASE_PORT: 5432
      DEBUG: "False"


    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: python manage.py test
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: AWS EC2 ga SSH orqali ulanish
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/soyibjon-diplom-ishi  
            git fetch origin main
            sudo chown -R ec2-user:ec2-user .        
            git reset --hard origin/main    # ← eski o'zgarishlarni bekor qiladi                    
             
             
                                
            docker build -t soyibjon-diplom-ishi-web:latest .
            docker tag soyibjon-diplom-ishi-web:latest soyibjon-diplom-ishi-celery:latest
            docker-compose up -d --no-build


            docker-compose exec -T web python manage.py migrate
            docker-compose exec -T web python manage.py collectstatic --noinput 
            docker system prune -f
